---
title: "ecdc covid vaccines uptake"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(lubridate)
library(janitor)
library(readxl)
library(openxlsx)
library(ggflags)
library(scales)
library(utils)

```

#Importing
```{r}

data <- read_csv("data.csv")%>%
  clean_names()%>%
  separate(year_week_iso,into=c("year","week"),sep="-",remove=F)%>%
  mutate(year_week_date=str_c(year_week_iso,"1",sep="-"))%>%
  mutate(year_week_date=ISOweek::ISOweek2date(year_week_date))%>%
  mutate(week=str_replace_all(week,"W",""))%>%
  select(year_week_date,everything())%>%
  mutate(total_doses=first_dose+second_dose)%>%
  mutate(target_group=as.factor(target_group),
         region=as.factor(region))

data_for_population <- read.csv("https://opendata.ecdc.europa.eu/covid19/nationalcasedeath_eueea_daily_ei/csv", na.strings = "", fileEncoding = "UTF-8-BOM")

countries_code <- read_excel("country codes.xlsx")%>%
  clean_names()%>%
  select(code,english)%>%
  rename(region=code)


## Important notes

# The denominator in the target group "ALL" does not refer in the population of adults over 18 in that country, as indicated in the ecdc site, but in the total population of the country (https://www.ecdc.europa.eu/sites/default/files/documents/Variable_Dictionary_VaccineTracker-04-11-2021.pdf)



```

#Greece
```{r}


# 

 data%>%
  filter(region=="EL")%>%
  group_by(target_group)%>%
  summarize(total=sum(total_doses))

# Greece, aggregation of categories only by age categories and uknown age

greece_total_doses <- data%>%
  filter(region=="EL")%>%
  filter(target_group %in% c("Age18_24","Age25_49","Age50_59","Age60_69","Age70_79","Age80+","AgeUNK"))%>%
  group_by(target_group)%>%
  summarize(total=sum(total_doses))
  
greece_first_dose <- data%>%
  filter(region=="EL")%>%
  filter(target_group %in% c("Age18_24","Age25_49","Age50_59","Age60_69","Age70_79","Age80+","AgeUNK"))%>%
  group_by(target_group)%>%
  summarize(total=sum(first_dose))
  
greece_first_dose_over_under_60 <- data%>%
  filter(region=="EL" & target_group %in% c("1_Age<60","1_Age60+","AgeUNK"))%>%
  group_by(target_group)%>%
  summarize(total=sum(first_dose))



# greece_total_doses%>%
#   left_join(greece_first_dose,by=c("target_group"),)%>%
#   mutate(difference=total.x-total.y)


# Greece, all categories, all doses

data%>%
  filter(region=="EL")%>%
  group_by(target_group)%>%
  summarize(total=sum(total_doses))
  
# Percentage of vaccine first dose uptake by age category (also those with unknown age)

data%>%
  filter(region=="EL")%>%
  filter(target_group %in% c("Age18_24","Age25_49","Age50_59","Age60_69","Age70_79","Age80+","AgeUNK"))%>%
  distinct(target_group,.keep_all = T)%>%
  select(target_group,denominator)%>%
  left_join(greece_first_dose,by=c("target_group"))%>%
  mutate(percentage=total/denominator*100)
  


# In the categories <60 and >60 are included everyone (also those with unknown age)

data%>%
  filter(region=="EL" & target_group %in% c("1_Age<60","1_Age60+"))%>%
  distinct(target_group,.keep_all = T)%>%
  select(target_group,denominator)%>%
  left_join(greece_first_dose_over_under_60,by=c("target_group"))%>%
  mutate(percentage=total/denominator*100)
  

# Percentage of over 18 that has taken at least one dose of the vaccine

total_first_dose_adults_greece <- data%>%
  filter(region == "EL")%>%
  group_by(target_group)%>%
  summarize(total_first_dose = sum(first_dose))%>%
  filter(target_group %in% c("Age18_24", "Age25_49", "Age50_59", "Age60_69", "Age70_79", "Age80+"))%>%
  summarize(total_first_dose_adults = sum(total_first_dose))%>%
  pull(total_first_dose_adults)

denominator_first_dose_adults_greece <- data%>%
  filter(region == "EL")%>%
  distinct(target_group, .keep_all = T)%>%
  select(target_group, denominator)%>%
  filter(target_group %in% c("Age18_24", "Age25_49", "Age50_59", "Age60_69", "Age70_79", "Age80+"))%>%
  summarize(denominator_adults = sum(denominator))%>%
  pull(denominator_adults)

total_first_dose_adults_greece / denominator_first_dose_adults_greece * 100

# Percentage of the total population with at least one dose

data%>%
  filter(region == "EL")%>%
  group_by(target_group)%>%
  summarize(total_first_dose = sum(first_dose))




```


# All countries
```{r}
# Total doses administered so far
data%>%
  group_by(target_group,region)%>%
  summarize(total=sum(total_doses))%>%
  arrange(desc(total))%>%
  filter(target_group=="ALL")

data%>%
  group_by(target_group,region)%>%
  summarize(total=sum(first_dose))%>%
  arrange(desc(total))%>%
  filter(target_group=="ALL")

# Total doses by age group

data%>%
  group_by(target_group,region)%>%
  summarize(total=sum(total_doses))%>%
  filter(target_group!="ALL" & target_group!="HCW")%>%
  arrange(desc(target_group))



## Europe first_doses doses by age category

eu_first_dose_age_categ <- data%>%
  filter(target_group %in% c("Age18_24","Age25_49","Age50_59","Age60_69","Age70_79","Age80+","AgeUNK"))%>%
  group_by(target_group,region)%>%
  summarize(total=sum(first_dose))

## Europe first doses of health care workers

eu_first_dose_hlws <- data%>%
  filter(target_group=="HCW")%>%
  group_by(target_group,region)%>%
  summarize(total=sum(first_dose))
  
## Europe first dose over under 60 
## Only 7 countires are included in the over-under 60 category, greece are one of them

eu_first_dose_over_under_60 <- data%>%
  filter(target_group %in% c("1_Age<60","1_Age60+","AgeUNK"))%>%
  group_by(target_group,region)%>%
  summarize(total=sum(first_dose))




# Percentage of vaccine first dose uptake by age category (also those with unknown age)

eu_first_dose_age_categ_perc <- data%>%
  filter(target_group %in% c("Age18_24","Age25_49","Age50_59","Age60_69","Age70_79","Age80+","AgeUNK"))%>%
  distinct(target_group,region,.keep_all = T)%>%
  select(target_group,region,denominator)%>%
  left_join(eu_first_dose_age_categ,by=c("target_group","region"))%>%
  mutate(percentage=total/denominator*100)

eu_first_dose_age_categ_perc_wide <- eu_first_dose_age_categ_perc%>%
  mutate(percentage=round(percentage,2))%>%
  filter(target_group!="AgeUNK")%>%
  select(-denominator,-total)%>%
  spread(key=target_group,value=percentage)%>%
  left_join(countries_code,by=c("region"))%>%
  select(region,country=english,everything())%>%
  filter(!is.na(country))
  
# Percentage of vaccine first dose uptake by health care workers

eu_first_dose_hlws_perc <- data%>%
  filter(target_group=="HCW")%>%
  distinct(target_group,region,.keep_all=T)%>%
  select(target_group,region,denominator)%>%
  left_join(eu_first_dose_hlws,by=c("target_group","region"))%>%
  mutate(percentage=total/denominator*100)

eu_first_dose_hlws_perc_wide <- eu_first_dose_hlws_perc%>%
  mutate(percentage=round(percentage,2))%>%
  select(-denominator,-total)%>%
  spread(key=target_group,value=percentage)%>%
  left_join(countries_code,by=c("region"))%>%
  select(region,country=english,everything())%>%
  filter(!is.na(country))


# In the categories <60 and >60 are included everyone (also those with unknown age)
# Only 7 countires are included in the over-under 60 category, greece are one of them

eu_first_dose_over_under_60_perc <- data%>%
  filter(target_group %in% c("1_Age<60","1_Age60+"))%>%
  distinct(target_group,region,.keep_all = T)%>%
  select(target_group,region,denominator)%>%
  left_join(eu_first_dose_over_under_60,by=c("target_group","region"))%>%
  mutate(percentage=total/denominator*100)


## First dose in adults over 18 years old

first_dose_adults <- data%>%
  group_by(target_group, region)%>%
  summarize(total_first_dose = sum(first_dose))%>%
  ungroup()%>%
  filter(target_group %in% c("Age18_24", "Age25_49", "Age50_59", "Age60_69", "Age70_79", "Age80+"))%>%
  group_by(region)%>%
  summarize(total_first_dose_adults = sum(total_first_dose))

denominator_first_dose_adults <- data%>%
  distinct(region, target_group, .keep_all = T)%>%
  select(region, target_group, denominator)%>%
  filter(target_group %in% c("Age18_24", "Age25_49", "Age50_59", "Age60_69", "Age70_79", "Age80+"))%>%
  group_by(region)%>%
  summarize(denominator_adults = sum(denominator))

adults_first_dose_perc <- first_dose_adults%>%
  left_join(denominator_first_dose_adults, by = c("region"))%>%
  mutate(percentage =  (total_first_dose_adults / denominator_adults) * 100 )%>%
  right_join(countries_code, by = c("region"))%>%
  select(region, country = english, percentage)

# Total population of countries

countries_population <- data%>%
  filter(target_group == "ALL")%>%
  distinct(region, .keep_all = T)%>%
  select(region, denominator)%>%
  filter(!is.na(denominator))%>%
  right_join(countries_code, by = c("region"))%>%
  select(region, country = english, population = denominator)

# First dose in the total population

first_dose_total_population <- data%>%
  filter(target_group %in% c("ALL", "Age<18"))%>%
  right_join(countries_code, by = c("region"))%>%
  rename(country = english)%>%
  group_by(region, country)%>%
  summarize(total_first_dose_total_population = sum(first_dose))%>%
  filter(!is.na(total_first_dose_total_population))%>%
  ungroup()%>%
  left_join(countries_population, by = c("region", "country"))%>%
  mutate(perc_first_dose_total_population = round(((total_first_dose_total_population / population) * 100), 2))%>%
  select(region, country, perc_first_dose_total_population)


## Europe first doses in ALL and per age category (combined tibbles)

europe_first_dose_final <- adults_first_dose_perc%>%
  left_join(eu_first_dose_age_categ_perc_wide,by=c("region","country"))%>%
  left_join(eu_first_dose_hlws_perc_wide,by=c("region","country"))%>%
  left_join(first_dose_total_population, by = c("region", "country"))%>%
  rename(Adults_over_18=percentage, Total_Population = perc_first_dose_total_population)%>%
  select(region, country, Total_Population, Adults_over_18, everything())%>%
  arrange(desc(Adults_over_18))%>% 
  mutate(Adults_over_18 = round(Adults_over_18, 2))%>%
  filter(!is.na(Total_Population))%>%
  mutate_at( 
    vars(starts_with("Age")), 
    funs(case_when( 
      . >= 100 ~ 100, 
      TRUE ~ .)))

## Europe first does in Adults over 18 and per age category uptake of first dose (2021-11-09)  

europe_first_dose_final%>%
  filter(!is.na(Adults_over_18))%>%
  mutate(Adults_over_18 = Adults_over_18 / 100)%>%
  mutate(region = if_else(region == "EL", "GR", region))%>%
  mutate(country = fct_reorder(country, Adults_over_18))%>%
  ggplot(aes(x = country, y = Adults_over_18))+
  geom_col(aes(fill = Adults_over_18), width = .3)+
  scale_fill_gradientn(colors = c("red2", "yellow", "skyblue1"), breaks = c("0.2", "0.75", "0.90", "1"), guide = F)+
  #scale_fill_gradientn(colours = colorspace::heat_hcl(10), guide = F)+
  #scale_fill_gradient2(low = muted("red"), mid = "orange", high = muted("blue"), midpoint = 0.7, guide = F)+
  scale_y_continuous(labels = percent_format(prefix = "", suffix = "%"))+
  geom_text(aes(label = round((Adults_over_18 * 100), 1), y = Adults_over_18 + 0.03), size = 4)+
  geom_flag(aes(country = str_to_lower(region)))+
  scale_country(guide = F)+
  coord_flip()+
  labs(x = "", 
       y = "",
       title = "% Uptake of at Least One dose in Adults",
       subtitle = "till 2021/11/28",
       legend.position = "none")+
  theme_minimal()
  



```


